### ISSUE TITLE
RetsApiError

### ISSUE THREAD

**Issue by bigoper** [opendoor-labs/rets#10]
Hi All,

How do I catch the RetsApiError?
It's not being recognized.

Thanks.

**Comment by martinxsliu** [comment]
You can import the exception and catch it like you would any other exception. Something like:

```python
from rets.errors import RetsApiError

try:
    rets_client.search(...)
except RetsApiError as e:
    print('caught code %i!' % e.reply_code)
```

Is this what you meant?

**Comment by aviivgi** [comment]
Yes.
Thank you!!!
