### ISSUE TITLE
I can't even run the basic function on your site

### ISSUE THREAD

**Issue by Esko918** [opendoor-labs/rets#25]
I don't know why this is happening but every time I just try and run client.get_metadata('class', resource='Property') in a python script I keep getting the error. b'<RETS ReplyCode="20513" ReplyText="Miscellaneous Error"/>\n'. Am I not setting some values I need to in the session? I know the server was just updated to rest 1.7.2. Any ideas on what I need to do?

**Comment by Esko918** [comment]
<RETS ReplyCode="20513" ReplyText="Miscellaneous Error"/>\n

**Comment by Esko918** [comment]
<RETS ReplyCode="20513" ReplyText="Miscellaneous Error"/>

**Comment by Esko918** [comment]
RETS ReplyCode="20513" ReplyText="Miscellaneous Error

**Comment by blakeembrey** [comment]
Closing this out, but if I had a guess I'd say `Property` isn't a valid class in the RETS feed you're connecting to so it's returning an error.
