### ISSUE TITLE
metadata returns empty tuple, get_resource returns error

### ISSUE THREAD

**Issue by Valachio** [opendoor-labs/rets#34]
After logging in, when I try to get metadata, I get an empty tuple.  When I try to use `get_resource`, I get the error `xml.etree.ElementTree.ParseError: no element found: line 1, column 0`.

It seems that no data is accessible to me after logging in.  Any tips on why this is happening?  Thanks in advance.

    client = RetsClient(
	login_url=login_url,
	username=username,
	password=password,
	rets_version='1.7',
    )
    
    print(client.metadata) # This returns empty tuple
    
    resource = client.get_resource('Property') # This returns the following error: xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by martinxsliu** [comment]
That sounds like your RETS server might not be returning valid XML. Could you use a debugger to see what the response from the server is?

Using ipython:

```py
client = ...
resource = client.get_resource('Property') # Exception is raised

# ipython magic function to drop you into the stack trace of the exception
%debug

# up and down commands take you up and down a frame. navigate to the parse_xml function
up

# See what the response body and headers are
response.content
response.headers
```

**Comment by Valachio** [comment]
@martinxsliu Hey Martin.  Just ran the operations you recommended.  Here are the response

For `response.content`, the response was simply `b''`

For `response.headers, the response was `{'RETS-Version': 'RETS/1.7', 'cache-control': 'private', 'Content-Type': 'text/xml;charset=utf-8', 'MIME-Version': '1.0', 'Date': 'Sun, 28 Oct 2018 04:02:48 GMT', 'RETS-Server': 'StratusRETS/1.7', 'Server': 'StratusRETS/1.7', 'Content-Length': '0'}`

**Comment by martinxsliu** [comment]
So the server isn't returning anything in its response, which is not what's expected according to the RETS standard. Unfortunately, a lot of these issues come down to small variations in server implementations.

You could try using the `RetsHttpClient` instead:
```py
from rets.http import RetsHttpClient

client = RetsHttpClient(
    login_url='http://my.rets.server/rets/login',
    username='username',
    password='password',
    # Alternatively authenticate using user agent password
    # user_agent='rets-python/0.3',
    # user_agent_password=''
)
client.login()

# This line should fail with the same exception!
client.get_metadata('resource')

# See if this works?
client.get_metadata('class', resource='Property')
```

Does your rets provider have any technical guidance? Does using another tool (e.g. https://github.com/summera/retscli) work?

**Comment by Valachio** [comment]
@martinxsliu I tried using `RetsHttpClient`.  Same error (`xml.etree.ElementTree.ParseError: no element found: line 1, column 0`) when I did `client.get_metadata('class', resource='Property')`.  

I did however manage to get things working with librets w/ Python bindings.  So I'll be sticking with that until any further issues come up.  I appreciate you taking the time to help.

**Comment by wimby** [comment]
Hey, I got similar issue with empty metadata, but the server returned code `20513: Miscellaneous Error`.
I find out that `RetsHttpClient` sends `id` and `type` lowercased in `_get_metadata` method (which according to this: https://www.nar.realtor/retsorg.nsf/retsproto1.7d6.pdf section 11.1.2, seems to be wrong).
With payload patched to `ID` and `Type` instead it worked like a charm.
cc @Valachio

**Comment by martinxsliu** [comment]
Closed by https://github.com/opendoor-labs/rets/pull/45
