### ISSUE TITLE
Not able to install on newer versions of Python 

### ISSUE THREAD

**Issue by janwelten** [opendoor-labs/rets#59]
Only tried Python 3.7 and 3.9.1

"Running setup.py install for udatetime ... error"

Found that udatetime will not install on later versions than 3.5 

Any workaround?

**Comment by blakeembrey** [comment]
We're using it on Python 3.6 and Python 3.7 without issue, let me get back to you.

**Comment by ccurvey** [comment]
There is an open issue on this for udatetime:  https://github.com/freach/udatetime/issues/32

**Comment by bperry** [comment]
This issue is still happening.

Perhaps udatetime needs removed as a dependency as it hasn't been updated since 2018

**Comment by janwelten** [comment]
Tried Python 3.7,  3.9.1 and 3.11
Still not able to install udatetime 0.0.17 during the process


collecting udatetime
  Using cached udatetime-0.0.17.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: udatetime
  Building wheel for udatetime (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\udatetime
      copying udatetime\_pure.py -> build\lib.win-amd64-3.8\udatetime
      copying udatetime\__init__.py -> build\lib.win-amd64-3.8\udatetime
      running egg_info
      writing udatetime.egg-info\PKG-INFO
      writing dependency_links to udatetime.egg-info\dependency_links.txt
      writing top-level names to udatetime.egg-info\top_level.txt
      reading manifest file 'udatetime.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'udatetime.egg-info\SOURCES.txt'
      running build_ext
      building 'udatetime.rfc3339' extension
      creating build\temp.win-amd64-3.8
      creating build\temp.win-amd64-3.8\Release
      creating build\temp.win-amd64-3.8\Release\src
      C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -D_PYTHON3=1 -IC:\Python\Python38\include -IC:\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tc./src/rfc3339.c /Fobuild\temp.win-amd64-3.8\Release\./src/rfc3339.obj -Ofast -std=c99
      cl : Command line warning D9025 : overriding '/Os' with '/Ot'
      cl : Command line warning D9002 : ignoring unknown option '-Of'
      cl : Command line warning D9002 : ignoring unknown option '-Oa'
      cl : Command line warning D9002 : ignoring unknown option '-std=c99'
      rfc3339.c
      ./src/rfc3339.c(278): warning C4244: 'function': conversion from 'std::size_t' to 'double', possible loss of data
      ./src/rfc3339.c(278): warning C4244: '=': conversion from 'double' to 'unsigned int', possible loss of data
      C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Python\Python38\libs /LIBPATH:C:\Python\Python38\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" m.lib /EXPORT:PyInit_rfc3339 build\temp.win-amd64-3.8\Release\./src/rfc3339.obj /OUT:build\lib.win-amd64-3.8\udatetime\rfc3339.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\./src\rfc3339.cp38-win_amd64.lib
      LINK : fatal error LNK1181: cannot open input file 'm.lib'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for udatetime
  Running setup.py clean for udatetime
Failed to build udatetime
