### ISSUE TITLE
docopts Python dependency unnecessary

### ISSUE THREAD

**Issue by queijeiro** [opendoor-labs/rets#62]
There is a dependency in `install_requires` in `setup.py` on `docopts`, but this package is not at all dependent on `docopts`. It is only lightly used in `bin/deploy` script which is not part of the library itself.

This causes problems in some popular dependency resolvers like [`pip-compile`](https://github.com/jazzband/pip-tools) as [`docopts`](https://github.com/docopt/docopts) moved from Python to Go in v0.6.2 and stopped publishing packages to PyPI. The unnecessary dependency on `docopts` Python package here brings in v0.6.1 which also brings in a pinned dependency on [`docopt`](https://github.com/docopt/docopt) (no 's') v0.6.1, which has been outdated since 2014 with v0.6.2 release.

Therefore, using any other Python library that depends on `docopt > 0.6.1` cannot be used alongside `rets-python` without causing conflicts in `pip-compile`.

Can `docopts` be removed from `install_requires` as it is not actually a dependency of the library?

**Comment by blakeembrey** [comment]
Thanks for the PR, it's merged.
